#!/bin/bash
echo "Listening Ports:"
echo "================"

listening_sockets=$(netstat -tlnp | awk '/^tcp/ || /^udp/ {print $4,$7}')

while read -r socket; do
ip_address=$(echo "$socket" | awk -F: '{print $1}')
port=$(echo "$socket" | awk -F: '{print $2}')
protocol=$(echo "$socket" | awk '{print $1}')

pid=$(lsof -i "$protocol:$port" -sTCP:LISTEN -sUDP:LISTEN -nP | awk '!/PID/ {print $2}')
program=$(lsof -i "$protocol:$port" -sTCP:LISTEN -sUDP:LISTEN -nP | awk '!/PID/ {print $1}')

echo "Protocol: $protocol"
echo "Port: $port"
echo "PID: $pid"
echo "Program: $program"
echo "----------------"
done <<< "$listening_sockets"

